### ISSUE TITLE
Track the source `Result` comes from

### ISSUE THREAD

**Issue by vrom911** [kowainik/trial#13]
Currently, I don't know how to do this. But we can brainstorm some ideas here, @chshersh

**Comment by chshersh** [comment]
I was thinking about adding a tag to `a` in `Result`. With the semantics of `Last` in the `Semigroup` instance, we will automatically get the tag of the latest `Result`. So I see several options here:

1. Add `tag` variable to the `Trial` itself:
    ```haskell
    data Trial tag e a = ... | Result [e] (tag, a)
    ```
2. Suggest users implementing the `Tag` type by themselves and have a type like `Trial MyError (SourceTag, a)` where:
    ```haskell
    data SourceTag
        = CLI
        | Config
        | Env
        | Def
    ```
3. We can implement a data type like `SourceTag` in the `trial-smth` package with all helpers for configuration formats.
