### ISSUE TITLE
Add more instances to Trial

### ISSUE THREAD

**Issue by vrom911** [kowainik/trial#2]
- `Alternative`
- `Bifunctor`
- `Bifoldable`
- `Bitraversable`
... maybe more

**Comment by chshersh** [comment]
Should we also add `Monoid`?

**Comment by vrom911** [comment]
That is a good question, I was thinking about that as well, but haven't decided on `mempty`. For `Alternative` it seems reasonable to me to use `Fiasco []`, not sure if it should be so for `Monoid`? I don't know if require `Monoid` for `a` is better in this case or not :thinking:

**Comment by chshersh** [comment]
@vrom911 Makes sense :+1:  Let's try without `Monoid` and add `Monoid` only if we need it for some reason.
