### ISSUE TITLE
Functions to convert DList to List at the end

### ISSUE THREAD

**Issue by chshersh** [kowainik/trial#25]
When users want to analyse resulting `Fiasco` and `Result`, they need to work with `DList` when they actually want to work with list. We need to provide some utilities for this.

A few options:

1. Create a function of type `Trial e a -> ([e], Maybe a)`
2. Create patterns `FiascoL` and `ResultL` which like the data type but with lists.
3. Reexport a function `DList a -> [a]`

**Comment by vrom911** [comment]
I would also add some filtering functions: `fiascoErrors` `fiascoWarnings`. What do you think?
