### ISSUE TITLE
Add 'fiascoOnEmpty'

### ISSUE THREAD

**Issue by chshersh** [kowainik/trial#46]
The following function is useful for CLI:

```haskell
fiascoOnEmpty :: IsString tag => tag -> Parser [a] -> Parser (TaggedTrial tag [a])
```

**Comment by chshersh** [comment]
In the real use case, I have two functions:

```haskell
foo :: IO (Trial e Config)
bar :: IO (Trial e Config)
```

I desperately want to write in a nice syntax something like this:

```hsakell
foo <|> bar
```

But `Alternative` instance for `IO` doesn't work that way... We can introduce a new operator, like, _lazy monadic alternative_ with the following type and semantics:

```haskell
<||> :: Monad m => m (Trial e a) -> m (Trial e a) -> m (Trial e a)
```

* If the first `Trial` is `Result` then **don't perform** second action, otherwise perform second and use `<|>` (or `<>`, depending on #50) on both values.

**Comment by vrom911** [comment]
I also noticed that the more general one is also useful. Currently in Stan we have this:

```haskell
    whenEmpty :: [a] -> Text -> TaggedTrial Text [a]
    whenEmpty res name = withTag "CLI" $ case res of
        [] -> fiasco $ "No CLI option specified for: " <> name
        xs -> pure xs
```

**Comment by chshersh** [comment]
@vrom911 Good catch! Maybe we can have a function like:

```haskell
fiascoOnEmpty :: (IsString tag, Foldable f) => tag -> f a -> TaggedTrial tag (f a)
```

and then we can implement both `whenEmpty` and `fiascoOnEmptyCliOption` using this function? Not sure, whether this exact type will work, but this is just an idea :thinking:
