### ISSUE TITLE
Change Alternative instance

### ISSUE THREAD

**Issue by chshersh** [kowainik/trial#50]
Current implementation:

https://github.com/kowainik/trial/blob/49ad9a0dfe25e4300a1d62e38cf1bf96e0b4e3d4/trial/src/Trial.hs#L298-L301

Proposal:

```haskell
    (<|>) :: Trial e a -> Trial e a -> Trial e a
    r@Result{}  <|> _           = r
    f@Fiasco{}  <|> r@Result{}  = f <> r
    (Fiasco e1) <|> (Fiasco e2) = Fiasco (e1 <> e2)
```

New semantics: return first `Result`, but also accumulate all previous `Fiasco`s.

**Comment by vrom911** [comment]
Let's first check is the new semantic would preserve all the laws. If not we still can add such function as I see how useful it could be sometimes :slightly_smiling_face:
