### ISSUE TITLE
Support GHC 9.0 and 9.2

### ISSUE THREAD

**Issue by uhbif19** [kowainik/trial#67]
Dependent of issue: https://github.com/kowainik/colourista/issues/73

**Comment by tomjaguarpaw** [comment]
Bumping the dependencies is all that seems to be required to get it to work all the way to 9.4 (though that also requires colourista, tomland and validation-selective to be brought up to date too).

https://github.com/kowainik/trial/compare/main...tomjaguarpaw:trial:9.4
