### ISSUE TITLE
Please make Hackage revision

### ISSUE THREAD

**Issue by tomjaguarpaw** [kowainik/trial#70]
Could you please bump the `base` version dependency on Hackage to `< 4.18` for `trial`, `trial-tomland` and `trial-optparse-applicative`? The `trial` packages work fine with GHC 9.4 at least without change (I haven't tried 9.6).

**Comment by tomjaguarpaw** [comment]
I can confirm that `9.6` works fine too (assuming `--allow-newer` to allow `colorista` to compile too), so `base < 4.19` will be fine.

**Comment by tomjaguarpaw** [comment]
Specifically, `trial`, `trial-optparse-applicative` and `trial-tomland` all of version `0.0.0.0` can be expanded to `base < 4.19`.

**Comment by andreasabel** [comment]
- https://hackage.haskell.org/package/trial-0.0.0.0/revisions/ Tested even with GHC 9.8.1-alpha1
- https://hackage.haskell.org/package/trial-tomland-0.0.0.0/revisions/ No tests in this package, builds with GHC 9.8.1-alpha
- https://hackage.haskell.org/package/trial-optparse-applicative-0.0.0.0/revisions/ No tests either, builds with GHC 9.8.1-alpha

**Comment by tomjaguarpaw** [comment]
Hackage is now up to date with GHC 9.8.
