### ISSUE TITLE
How to abstract lists inside the trial?

### ISSUE THREAD

**Issue by vrom911** [kowainik/trial#8]
Could we do better than list? Should we make this switchable to users?

**Comment by chshersh** [comment]
I see two ways to abstract lists:

1. Easy-way: `data Trial m a = Fiasco m | ...` and require `Semigroup/Monoid` for `m`
2. Fancy way: `data Trial (f :: k -> Type) (e :: k) a = Fiasco (f e) | ...` so people can have not only lists, but `NonEmpty` or even `Int` and `Text` with a custom type family in place of `f`

**Comment by chshersh** [comment]
With the `Fatality` implemented, those abstractions are not really the ways to go... But as discussed with @vrom911, we can use difference list for faster appending.

**Comment by vrom911** [comment]
We can consider using difference lists, as most of the time we are contaminating `e`s:
* https://hackage.haskell.org/package/dlist

We should also provide useful functions for work with `e`s for users if we go with this option.
